#     NeoChat
#  Permission nodes
#    neochat.<chatName>.use Allows for Using and Seeing the chat
#    neochat.<chatName>.see Allows for Seeing the chat
#    neochat.<chatName>.color Allows for the parsing of color in the chat (auto-format still applied)
#    neochat.<chatName>.format Allows or the parsing of format in the chat (auto-format still applied)
#    neochat.<chatName>.toggle Allows the user to toggle into another chat. 
#  chatName:
#    command: 'command' (Required)
#    prefix: 'something' 
#    auto-format: 'formatting'
#    show-names: booleanValue
chat-channels:
  staff:
    command: 'sc'
    prefix: '&8&l[&c&lStaff&8&l]'
    auto-format: '&6'
    show-names: true
  donor:
    command: 'dc'
    prefix: '&8[&aDonor&8]'
    auto-format: '&6'
  announce:
    command: 'an'
    prefix: '&a&l[&b&lAnnouncement&a&l]'
    auto-format: '&e&l'
    show-names: false
Auto-Toggle: