name: NeoChat
version: 1.5.0
author: REGAL_MACHINE
main: me.RegalMachine.NeoChat.NeoChat
depend: [Essentials]
dev-url: http://dev.bukkit.org/bukkit-plugins/neochat/
commands:
  color:
    description: Shows the bukkit colors codes. /format for format codes.
  format:
    description: Shows the bukkit format codes. /color for color codes.
  chats:
    description: Simple help command for the registered chats and other NeoChat features.